spring.datasource.url=jdbc:mysql://localhost:3306/autocestadb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=application-secret.properties

platerecognizer.api.url=https://api.platerecognizer.com/v1/plate-reader/